{
 "title": "Databases",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "compartment", "label": "Compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "a",
    "label": "a",
    "query": "metrics($region,$compartment, $namespace, $resource)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "MonitoringStatus",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "MonitoringStatus[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "intervalLabel": "Auto",
     "legendFormat": "{{resourceName}}",
     "metric": "StorageUtilization",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "StorageUtilization[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - OCPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{instanceName}}",
     "metric": "OcpusAllocated",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "cpu-core-count",
     "queryTextRaw": "cpu-core-count",
     "region": "sa-saopaulo-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Sessions",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{instanceName}}",
     "metric": "SessionLimitUtilization",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "SessionLimitUtilization[1m].avg()",
     "queryTextRaw": "cpu-core-count",
     "region": "sa-saopaulo-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Processes",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{instanceName}}",
     "metric": "ProcessLimitUtilization",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "ProcessLimitUtilization[1m].avg()",
     "queryTextRaw": "cpu-core-count",
     "region": "sa-saopaulo-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Average Active Sessions",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "DBTime",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "DBTime[1m].avg()",
     "region": "sa-saopaulo-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Average Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "DBTime",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "DBTime[1m].avg()",
     "region": "sa-saopaulo-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Sessions",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "Sessions",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "Sessions[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{resourceName}}",
     "metric": "Sessions",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "Sessions[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databses - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "CpuUtilization",
     "metricNames": [
      "BlockChanges",
      "CpuUtilization",
      "CurrentLogons",
      "ExecuteCount",
      "ParseCount",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "UserCalls"
     ],
     "namespace": "oci_database",
     "queryText": "CpuUtilization[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databses - CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "CpuUtilization",
     "metricNames": [
      "BlockChanges",
      "CpuUtilization",
      "CurrentLogons",
      "ExecuteCount",
      "ParseCount",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "UserCalls"
     ],
     "namespace": "oci_database",
     "queryText": "CpuUtilization[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "MemoryUtilization",
     "metricNames": [
      "ASMDiskgroupUtilization",
      "CpuUtilization",
      "FilesystemUtilization",
      "LoadAverage",
      "MemoryUtilization",
      "NodeStatus",
      "OcpusAllocated",
      "SwapUtilization"
     ],
     "namespace": "oci_database_cluster",
     "queryText": "MemoryUtilization[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "MemoryUtilization",
     "metricNames": [
      "ASMDiskgroupUtilization",
      "CpuUtilization",
      "FilesystemUtilization",
      "LoadAverage",
      "MemoryUtilization",
      "NodeStatus",
      "OcpusAllocated",
      "SwapUtilization"
     ],
     "namespace": "oci_database_cluster",
     "queryText": "MemoryUtilization[1m].avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Read/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Read\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOPS",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOPS[1m]{ioType=\"Read\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Write/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "w/s" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Write\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOPS",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOPS[1m]{ioType=\"Write\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Read/s",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Read\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOPS",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOPS[1m]{ioType=\"Read\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases - Write/s",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "w/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Write\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOPS",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOPS[1m]{ioType=\"Write\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases -Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Read\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOThroughput",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOThroughput[1m]{ioType=\"Read\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Databases -Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "compartment": "ocid1.compartment.oc1..aaaaaaaaso7oxa4qvx7jfkcamumlsw4ylaeiarfo7ojzypzg7jot2khosqvq",
     "compartmentName": "transoft38018 > Transnet",
     "dimensionValues": [
      "ioType=\"Write\""
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}}",
     "metric": "IOThroughput",
     "metricNames": [
      "AllocatedStorageUtilizationByTablespace",
      "BackupDuration",
      "BackupSize",
      "BlockChanges",
      "CPUTime",
      "CpuCount",
      "CpuUtilization",
      "CurrentLogons",
      "DBTime",
      "ExecuteCount",
      "FRASpaceLimit",
      "FRAUtilization",
      "IOPS",
      "IOThroughput",
      "LogicalBlocksRead",
      "MaxTablespaceSize",
      "MemoryUsage",
      "MonitoringStatus",
      "MonitoringUserPasswordExpiration",
      "NonReclaimableFRA",
      "OcpusAllocated",
      "ParseCount",
      "ParsesByType",
      "ProcessLimitUtilization",
      "Processes",
      "ReclaimableFRA",
      "ReclaimableFRASpace",
      "RecoveryWindow",
      "RedoGenerationRate",
      "RedoSize",
      "RetentionPeriod",
      "SessionLimitUtilization",
      "Sessions",
      "StorageAllocated",
      "StorageAllocatedByTablespace",
      "StorageUsed",
      "StorageUsedByTablespace",
      "StorageUtilization",
      "StorageUtilizationByTablespace",
      "TransactionCount",
      "TransactionsByStatus",
      "UnprotectedDataWindow",
      "UsableFRA",
      "UsedFRASpace",
      "UserCalls",
      "WaitTime"
     ],
     "namespace": "oracle_oci_database",
     "queryText": "IOThroughput[1m]{ioType=\"Write\"}.avg()",
     "region": "sa-saopaulo-1",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}